CREATE TABLE email_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(128) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    run_id BIGINT NOT NULL,
    stage_attempt_no INTEGER NOT NULL,
    requested_by BIGINT NOT NULL,
    delivery_type VARCHAR(40) NOT NULL,
    recipient VARCHAR(254) NOT NULL,
    recipient_normalized VARCHAR(254) NOT NULL,
    status VARCHAR(30) NOT NULL,
    provider VARCHAR(30),
    provider_message_id VARCHAR(255),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    failure_code VARCHAR(80),
    failure_reason VARCHAR(1000),
    sample_sha256 CHAR(64) NOT NULL,
    template_version VARCHAR(40) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_email_deliveries_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_email_deliveries_stage_attempt_positive CHECK (stage_attempt_no > 0),
    CONSTRAINT ck_email_deliveries_attempt_count_nonnegative CHECK (attempt_count >= 0),
    CONSTRAINT ck_email_deliveries_type CHECK (delivery_type IN ('SELECTION_SAMPLE')),
    CONSTRAINT ck_email_deliveries_status CHECK (
        status IN ('QUEUED', 'SENDING', 'SENT', 'RETRYING', 'FAILED')
    )
);

CREATE UNIQUE INDEX uq_email_deliveries_active_request
    ON email_deliveries (run_id, stage_attempt_no, recipient_normalized, delivery_type)
    WHERE status IN ('QUEUED', 'SENDING', 'RETRYING');

CREATE INDEX ix_email_deliveries_run_id ON email_deliveries (run_id);
CREATE INDEX ix_email_deliveries_status_updated_at ON email_deliveries (status, updated_at);

COMMENT ON TABLE email_deliveries IS 'Spring이 단독 소유하는 고객 이메일 발송 이력';
COMMENT ON COLUMN email_deliveries.run_id IS 'FastAPI PipelineRun 식별자이며 교차 서비스 FK를 생성하지 않음';
COMMENT ON COLUMN email_deliveries.sample_sha256 IS '발송 요청의 합성 샘플 스냅샷 SHA-256; 샘플 원문은 저장하지 않음';
